#!/bin/bash

file_names=(
    "metadata_CHG.Col-0.wt.aerial-part.csv"
    "metadata_CHG.Col-0.wt.embryo.csv"
    "metadata_CHG.Col-0.wt.endosperm.csv"
    "metadata_CHG.Col-0.wt.immature-flower-buds.csv"
    "metadata_CHG.Col-0.wt.inflorescence.csv"
    "metadata_CHG.Col-0.wt.root.csv"
    "metadata_CHG.Col-0.wt.rosette.csv"
    "metadata_CHG.Col-0.wt.shoot.csv"
    "metadata_CHG.Col-0.wt.sperm-cell.csv"
    "metadata_CHG.Col-0.wt.vegetative-nucleus.csv"
    "metadata_CHG.Col-0.wt.whole-organism.csv"
    "metadata_CHH.Col-0.wt.aerial-part.csv"
    "metadata_CHH.Col-0.wt.embryo.csv"
    "metadata_CHH.Col-0.wt.endosperm.csv"
    "metadata_CHH.Col-0.wt.immature-flower-buds.csv"
    "metadata_CHH.Col-0.wt.inflorescence.csv"
    "metadata_CHH.Col-0.wt.root.csv"
    "metadata_CHH.Col-0.wt.rosette.csv"
    "metadata_CHH.Col-0.wt.shoot.csv"
    "metadata_CHH.Col-0.wt.sperm-cell.csv"
    "metadata_CHH.Col-0.wt.vegetative-nucleus.csv"
    "metadata_CHH.Col-0.wt.whole-organism.csv"
    "metadata_CpG.Col-0.wt.aerial-part.csv"
    "metadata_CpG.Col-0.wt.embryo.csv"
    "metadata_CpG.Col-0.wt.endosperm.csv"
    "metadata_CpG.Col-0.wt.immature-flower-buds.csv"
    "metadata_CpG.Col-0.wt.inflorescence.csv"
    "metadata_CpG.Col-0.wt.root.csv"
    "metadata_CpG.Col-0.wt.rosette.csv"
    "metadata_CpG.Col-0.wt.shoot.csv"
    "metadata_CpG.Col-0.wt.sperm-cell.csv"
    "metadata_CpG.Col-0.wt.vegetative-nucleus.csv"
    "metadata_CpG.Col-0.wt.whole-organism.csv"
)



for chrom in {1..5}; do  

  # Define the directory
  dir="/shares/grossniklaus.botinst.uzh/eharputluoglu/newShannonFilesDir/shannonFiles${chrom}"
  
  # Check if the directory doesn't exist and create it
  if [ ! -d "$dir" ]; then
    mkdir -p "$dir"
  fi

  # Loop through all files
  for input_file in "${file_names[@]}"; do
    output_file="$dir/output_${input_file}"

    # Only run the command if the output file doesn't already exist
    if [ ! -f "$output_file" ]; then
      ./shannon div -m "../meta-methylome/results/tables/metadata/${input_file}" -o "${output_file}" -s "$chrom" -c 5 6 -n 5mC C
    else
      echo "File $output_file exists!"
    fi
  done
done

echo "All Files are created!"